before_install:
  - lsb_release -a
  
dist: xenial

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install: 
  - pip3 install -r requirements.txt

script:
  - python3 -m unittest -q tests.test_ecr2ecr.AuthDataProps_Tests -v

  